import { describe, expect, it } from "vitest";
import { analyseWorkspace } from "../src/analysis";
import { AUTOSAVE_KEY, loadAutosave, saveAutosave } from "../src/autosave";
import { formatCidr, keyOf, parseCidr } from "../src/cidr";
import { allocateLeaf, createWorkspace, discoverJoinCandidates, splitLeaf, validateWorkspace } from "../src/model";
import { createPlanPreview } from "../src/plan-preview";
import { createReportHtml, createReportMarkdown } from "../src/report";
import { SCENARIOS } from "../src/scenarios";

function memoryStorage(): Storage {
  const values = new Map<string, string>();
  return {
    get length() { return values.size; },
    clear: () => values.clear(),
    getItem: (key) => values.get(key) ?? null,
    key: (index) => [...values.keys()][index] ?? null,
    removeItem: (key) => { values.delete(key); },
    setItem: (key, value) => { values.set(key, value); },
  };
}

describe("publication polish domain helpers", () => {
  it("allocates an individual leaf with deterministic metadata and supports reuse", () => {
    const root = createWorkspace(parseCidr("192.168.1.0/24"));
    const split = splitLeaf(root, keyOf(root.envelope), 26).state!;
    const first = allocateLeaf(split, keyOf(split.leaves[0]!), "Staff", 40).state!;
    const group = first.groups[0]!;
    expect(group.color).toMatch(/^#[0-9a-f]{6}$/);
    expect(group.requestedHosts).toBe(40);
    const second = allocateLeaf(first, keyOf(first.leaves[1]!), "", undefined, group.id).state!;
    expect(second.groups).toHaveLength(1);
    expect(second.leaves.filter((leaf) => leaf.allocationGroupId === group.id)).toHaveLength(2);
  });

  it("discovers pair and multi-level aligned join candidates", () => {
    const root = createWorkspace(parseCidr("10.0.0.0/24"));
    const split = splitLeaf(root, keyOf(root.envelope), 26).state!;
    const candidates = discoverJoinCandidates(split, keyOf(split.leaves[0]!)).candidates;
    expect(candidates.map((candidate) => formatCidr(candidate.cidr))).toEqual(["10.0.0.0/25", "10.0.0.0/24"]);
    expect(candidates[1]?.leafKeys).toHaveLength(4);
  });

  it("commits the exact state generated by a successful plan preview", () => {
    const root = createWorkspace(parseCidr("10.0.0.0/24"));
    const preview = createPlanPreview(root, [
      { label: "Web", prefix: 26, count: 1, requestedHosts: 50 },
      { label: "Data", prefix: 27, count: 1, requestedHosts: 20 },
    ], "closest");
    expect(preview.ok).toBe(true);
    expect(preview.steps).toHaveLength(6);
    expect(preview.proposedLeafKeys).toHaveLength(2);
    expect(validateWorkspace(preview.state!)).toEqual([]);
  });

  it("measures requested-host waste and contiguous free regions without guessing", () => {
    const root = createWorkspace(parseCidr("192.168.2.0/24"));
    const split = splitLeaf(root, keyOf(root.envelope), 26).state!;
    const staff = allocateLeaf(split, keyOf(split.leaves[0]!), "Staff", 40).state!;
    const unknown = allocateLeaf(staff, keyOf(staff.leaves[2]!), "Lab").state!;
    const analysis = analyseWorkspace(unknown);
    expect(analysis.measuredWaste).toBe(22);
    expect(analysis.unknownRequestAllocations).toBe(1);
    expect(analysis.freeRegionCount).toBe(2);
    expect(formatCidr(analysis.largestAvailable!)).toBe("192.168.2.64/26");
  });

  it("constructs every bundled scenario as a valid canonical workspace", () => {
    const preferences = createWorkspace(parseCidr("192.168.1.0/24")).preferences;
    expect(SCENARIOS).toHaveLength(6);
    for (const scenario of SCENARIOS) expect(validateWorkspace(scenario.build(preferences)), scenario.title).toEqual([]);
  });

  it("validates autosaves and safely removes corrupt local records", () => {
    const storage = memoryStorage();
    const state = createWorkspace(parseCidr("172.16.0.0/16"));
    saveAutosave(state, storage);
    expect(loadAutosave(storage)?.workspace).toEqual(state);
    storage.setItem(AUTOSAVE_KEY, "not-json");
    expect(loadAutosave(storage)).toBeNull();
    expect(storage.getItem(AUTOSAVE_KEY)).toBeNull();
  });

  it("escapes hostile labels in standalone HTML and Markdown reports", () => {
    const root = createWorkspace(parseCidr("192.168.1.0/24"));
    const hostile = '<img src=x onerror="globalThis.pwned=true">';
    const allocated = allocateLeaf(root, keyOf(root.envelope), hostile).state!;
    const html = createReportHtml(allocated);
    const markdown = createReportMarkdown(allocated);
    expect(html).not.toContain(`<td>${hostile}</td>`);
    expect(html).toContain("&lt;img");
    expect(markdown).not.toContain(hostile);
    expect(markdown).toContain("&lt;img");
  });
});
